# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2019

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

# - task: DotNetCoreCLI@2
#   displayName: 'Run Tests'
#   inputs:
#     command: test
#     projects: '**/*.csproj'
  
- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

# - task: SpecFlowPlus@0
#   condition: succeededOrFailed()
#   inputs:
#     generatorSource: 'FeatureFolder'
#     projectFilePath: 'testing'
#     testExecutionJson: '$(Build.SourcesDirectory)\testing\bin\Debug\TestExecution.json'
  
- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  displayName: 'Publish Report Artifact'
  inputs:
    pathtoPublish: 'testing/Report'
    artifactName: 'TestReport'
